CREATE OR REPLACE PACKAGE ENTITIES_PKG AS

/*
*   Author: Dario Botkuljak
*   Version: 1.0.1
*/

    PROCEDURE INSERT_MASTER_REC(P_SOME_KEY IN NUMBER,
                                P_MASTER_DESC IN VARCHAR2,
                                P_MASTER_ID OUT NUMBER);

    FUNCTION MASTER_EXIST(P_MASTER_ID IN NUMBER) RETURN NUMBER;
    
    FUNCTION MASTER_EXIST_2(P_MASTER_ID IN NUMBER) RETURN NUMBER;
END ENTITIES_PKG;